version: '3'

services:
  backend:
    build:
      context: ./backend
      target: dev
    tty: true
    working_dir: /opt/server
    volumes:
      - ./backend:/opt/server
      - ./static:/opt/static
    env_file:
      - .env
    expose:
      - '3000'
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data
    expose:
      - '5432'
    restart: always

  nginx:
    container_name: proxy_nginx
    depends_on:
      - backend
      - db
      - pgadmin
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: whynot@whynot.ru
      PGADMIN_DEFAULT_PASSWORD: whynotishe777
    expose:
      - '80'
    restart: always